apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: agent-kube-operator
    app.kubernetes.io/part-of: agent-kube-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: controller-manager
  name: {{ include "agentkube-operator-charts.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agentkube-operator-charts.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "agentkube-operator-charts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}