apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: agent-kube-operator
    app.kubernetes.io/part-of: agent-kube-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "agentkube-operator-charts.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agentkube-operator-charts.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "agentkube-operator-charts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}