apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: agent-kube-operator
    app.kubernetes.io/part-of: agent-kube-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "agentkube-operator-charts.fullname" . }}-manager-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]