{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentkube-operator-charts.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: agent-kube-operator
    app.kubernetes.io/part-of: agent-kube-operator
    {{- include "agentkube-operator-charts.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}